name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          
      - name: Install system dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libclang-dev
          
      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install llvm
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      # Run all tests
      - name: Run all tests
        run: cargo test --all --features vendored-sqlite
        
      # Run unit tests for specific modules
      - name: Run unit tests
        run: |
          cargo test --lib transaction --features vendored-sqlite
          cargo test --lib index --features vendored-sqlite
          cargo test --lib fts --features vendored-sqlite
          cargo test --lib json_store --features vendored-sqlite
          cargo test --lib mvcc --features vendored-sqlite
        
      # Build examples to ensure they compile
      - name: Build examples
        run: |
          cargo build --example advanced_features --features vendored-sqlite || true
          cargo build --example full_features_demo --features vendored-sqlite || true

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libclang-dev
          
      - name: Run clippy
        run: cargo clippy --features vendored-sqlite -- -D warnings